"""Add progress fields to habits

Revision ID: 5915f19af867
Revises: fcd60f182c78
Create Date: 2026-07-26 14:44:54.635784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5915f19af867'
down_revision: Union[str, None] = 'fcd60f182c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('max_days', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('last_updated', sa.Date(), nullable=True))
    op.add_column('habits', sa.Column('last_completed', sa.Date(), nullable=True))
    op.add_column('habits', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('habits', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'chat_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('habits', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('habits', 'completed_at')
    op.drop_column('habits', 'last_completed')
    op.drop_column('habits', 'last_updated')
    op.drop_column('habits', 'max_days')
    # ### end Alembic commands ###
