"""Add completed_early field

Revision ID: 5cc11bbaa078
Revises: 69548a09e5a4
Create Date: 2026-07-28 21:53:00.122971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc11bbaa078'
down_revision: Union[str, None] = '69548a09e5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('completed_early', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'completed_early')
    # ### end Alembic commands ###
